### ISSUE TITLE
[Bug]: subscribe_data_points decorator emits data before update

### ISSUE THREAD

**Issue by AkhilTThomas** [eclipse-velocitas/vehicle-app-python-sdk#47] opened 2022-12-19 13:27 UTC
### What happened?

When using the `@subscribe_data_points` decorator expectation is that the decorated function gets called whenever there is a change in the value in databroker.
But the behavior is that for the very first time the function is called regardless of update in the databroker.

Ex: 
`@subscribe_data_points("Vehicle.CurrentLocation.Latitude")`
`async def do_something(self, data: DatapointReply):`
      ` trigger_some_action(data.get(Vehicle.CurrentLocation.Latitude).value)`

Here the `trigger_some_action' will get called with initial values from the databroker, which i do not want.

Is this an intentional design or an oversight?

### Operating System

Linux

### What release version or branch did you use?

0.7.1

### Code of Conduct

- [X] I agree to follow this project's rules for contributions

**Comment by gkreyssing** [comment] 2022-12-20 08:57
@BjoernAtBosch: Could you please answer the question above?

**Comment by BjoernAtBosch** [comment] 2022-12-21 10:10
Hi Thomas,
thanks for your input.

Getting the current value of a data point immediately after subscription is intended behaviour (and quite common with pub-sub-patterns): With that you get to know the current state of a data point and later receive notifications when the value changes.
Without that behaviour you would need to do an additional "get" call before or after the subscription which can end up with nitty-gritty race conditions.

So, I will close this bug report.

Please feel free to share your opinion, if you think this behaviour should be changed and why an initial notification after the subscribe is "a bad thing".

Regards,
Björn

**Closed by BjoernAtBosch** 2022-12-21 10:10 UTC
Labels: bug
